### ISSUE TITLE
Error when showing Dialog with UltraMap and closing before loading

### ISSUE THREAD

**Issue by Abdulrahmanmarzooq** [WissamALSbenaty/Ultra-Map-Place-Picker#4]
Hi,

I have encountered an error related to this package, basically, putting this in a bottomSheetModal works fine, but if the picker is not loaded fully and a user closes the dialog, it crashes the entire app and it becomes unusable with the below error repeating with any click.
```
E/flutter (14477): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5350 pos 12: '!_debugLocked': is not true.
E/flutter (14477): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:50:61)
E/flutter (14477): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (14477): #2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5350:12)
E/flutter (14477): #3      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:5316:9)
E/flutter (14477): <asynchronous suspension>
```

**Comment by WissamALSbenaty** [comment]
Hi @Abdulrahmanmarzooq 

Sorry for that

Could you please provide a code snippet ?
Thanks

**Comment by tiltmaster** [comment]
> Hi @Abdulrahmanmarzooq
> 
> Sorry for that
> 
> Could you please provide a code snippet ? Thanks

I have managed to do so here:

```
 showJustBottomSheet(
    context: context,
    dragZoneConfiguration: JustBottomSheetDragZoneConfiguration(
      dragZonePosition: DragZonePosition.inside,
      child: ClipRRect(
        borderRadius: BorderRadius.circular(4),
        child: Container(
          height: 4,
          width: 30,
          color: Theme.of(context).colorScheme.surface,
        ),
      ),
    ),
    configuration: JustBottomSheetPageConfiguration(
      height: MediaQuery.of(context).size.height * 0.95,
      builder: (context) {
        return UltraMapPlacePicker(
          googleApiKey: "KEY VALUE",
          initialPosition: LocationModel(25.1974767426511, 55.279669543133615),
          mapTypes: (isHuaweiDevice) => isHuaweiDevice ? [UltraMapType.normal] : UltraMapType.values,
          myLocationButtonCooldown: 1,
          resizeToAvoidBottomInset: false,
          useCurrentLocation: true,
          onPlacePicked: (value) {},
          enableMapTypeButton: false,
          hidePlaceDetailsWhenDraggingPin: false,
          selectInitialPosition: true,
          onTapBack: () => Navigator.pop(context),

          selectedPlaceWidgetBuilder: (context, selectedPlace, state, isSearchBarFocused) {....}
```

**Comment by tiltmaster** [comment]
I just wanted to let you know that this is due to another package. this should be closed. (commenting from my second account) XD

> Hi @Abdulrahmanmarzooq
> 
> Sorry for that
> 
> Could you please provide a code snippet ? Thanks
